### ISSUE TITLE
The token '&&' is not a valid statement separator in this version.

### ISSUE THREAD

**Issue by SkySibe** [Esshahn/acme-assembly-vscode-template#7]
I have download 'acme-assembly-vscode-template-master',
also VICE 3.4 (from: https://vice-emu.sourceforge.io/index.html#download)
and excracted the files into C:\tools\vice
also I did download the Acme Cross Assembler extension for VSCode,
after all of that I tried to run the main.asm
but it's showed this error:
```
> Executing task: bin\win\acme -f cbm -l build/labels -o build/main.prg code/main.asm && C:/tools/vice/x64.exe -moncommands build/labels build/main.prg <

At line:1 char:69
+ ... cme -f cbm -l build/labels -o build/main.prg code/main.asm && C:/tool ...
+                                                                ~~
The token '&&' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine
 
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```
I changed ```&&``` to ```-and``` but it's didn't work either...

**Comment by Esshahn** [comment]
I take you're on Windows? It may be related to the issue I wrote about in the readme:

Windows Command Line Syntax
Some Windows Users had issues with the Command Line Chaining and found out that replacing the && with ; works. So instead of

"command": "bin\\win\\acme -f cbm -l build/labels -o build/main.prg code/main.asm && C:/tools/vice/x64.exe -moncommands build/labels build/main.prg"

try

"command": "bin\\win\\acme -f cbm -l build/labels -o build/main.prg code/main.asm ; C:/tools/vice/x64.exe -moncommands build/labels build/main.prg"



Hope that helps.

**Comment by henrikp** [comment]
Had the same issue as OP and replacing && with ; fixed it.
